package com.github.typingtanuki.ids.snort.options;

public enum SnortOptionType {
    msg,
    sid,
    rev,
    classtype,
    flags,
    activated_by,
    count,
    content,
    nocase,
    flow,
    urilen,
    fast_pattern,
    pcre,
    http_header,
    flowbits,
    metadata,
    reference,
    file_data,
    depth,
    dsize,
    within,
    distance,
    http_uri,
    http_method,
    detection_filter,
    byte_jump,
    http_client_body,
    isdataat,
    offset,
    http_cookie,
    http_stat_code,
    itype,
    http_raw_uri
}
